name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: chmod
      run: sudo chmod +x ./git.sh
      
    - name: run
      run: ./git.sh

      
